List<Map<String, dynamic>> bookData = [
  {
    "id": 43132,
    "title": "Northanger Abbey",
    "author": "Austen, Jane",
    "year_written": 1814,
    "edition": "Penguin",
    "price": 18.2,
    "count": 5,
    "lent": 3,
  },
  {
    "id": 67647,
    "title": "War and Peace",
    "author": "Tolstoy, Leo",
    "year_written": 1865,
    "edition": "Penguin",
    "price": 12.7,
    "count": 5,
    "lent": 4,
  },
  {
    "id": 12353,
    "title": "Anna Karenina",
    "author": "Tolstoy, Leo",
    "year_written": 1875,
    "edition": "Penguin",
    "price": 13.5,
    "count": 5,
    "lent": 5,
  },
  {
    "id": 29438,
    "title": "Mrs. Dalloway",
    "author": "Woolf, Virginia",
    "year_written": 1925,
    "edition": "Harcourt Brace",
    "price": 25,
    "count": 5,
    "lent": 5,
  },
  {
    "id": 24242,
    "title": "The Hours",
    "author": "Cunnningham, Michael",
    "year_written": 1999,
    "edition": "Harcourt Brace",
    "price": 12.35,
    "count": 5,
    "lent": 1,
  },
  {
    "id": 67368,
    "title": "Huckleberry Finn",
    "author": "Twain, Mark",
    "year_written": 1865,
    "edition": "Penguin",
    "price": 5.76,
    "count": 5,
    "lent": 3,
  },
  {
    "id": 92380,
    "title": "Bleak House",
    "author": "Dickens, Charles",
    "year_written": 1870,
    "edition": "Random House",
    "price": 5.75,
    "count": 5,
    "lent": 4,
  },
  {
    "id": 90321,
    "title": "Tom Sawyer",
    "author": "Twain, Mark",
    "year_written": 1862,
    "edition": "Random House",
    "price": 7.75,
    "count": 5,
    "lent": 2,
  },
  {
    "id": 52572,
    "title": "A Room of One's Own",
    "author": "Woolf, Virginia",
    "year_written": 1922,
    "edition": "Penguin",
    "price": 29,
    "count": 5,
    "lent": 4,
  },
  {
    "id": 28344,
    "title": "Harry Potter",
    "author": "Rowling, J.K.",
    "year_written": 2000,
    "edition": "Harcourt Brace",
    "price": 19.95,
    "count": 5,
    "lent": 5,
  },
  {
    "id": 11223,
    "title": "One Hundred Years of Solitude",
    "author": "Marquez",
    "year_written": 1967,
    "edition": "Harper  Perennial",
    "price": 14.00,
    "count": 5,
    "lent": 1,
  },
  {
    "id": 66613,
    "title": "Hamlet, Prince of Denmark",
    "author": "Shakespeare",
    "year_written": 1603,
    "edition": "Signet  Classics",
    "price": 7.95,
    "count": 5,
    "lent": 5,
  },
  {
    "id": 77242,
    "title": "Lord of the Rings",
    "author": "Tolkien, J.R.",
    "year_written": 1937,
    "edition": "Penguin",
    "price": 27.45,
    "count": 5,
    "lent": 3,
  },
];
